// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package home

import (
	"github.com/go-ex/gin-proto/app/logics/login"
)

// Injectors from home.controller.wire.go:

func InitializeNewHomeProvider() *Home {
	account := login.InitializeNewAccountProvider()
	home := NewHomeProvider(account)
	return home
}
