// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package provoders

// Injectors from wire.go:

// GetApp 注入声明
func GetApp() *app {
	provodersConfig := InitConfig()
	provodersDatabase := InitDb(provodersConfig)
	provodersApp := InitApp(provodersDatabase, provodersConfig)
	return provodersApp
}
