// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package routes

import (
	"github.com/go-ex/gin-proto/app/http/controllers/home"
	"github.com/go-ex/gin-proto/app/http/controllers/login"
)

// Injectors from controllers.wire.go:

func InitializeNewControllersRoutesProvider() *ControllersRoutes {
	homeHome := home.InitializeNewHomeProvider()
	loginLogin := login.InitializeNewLoginProvider()
	controllersRoutes := NewControllersRoutesProvider(homeHome, loginLogin)
	return controllersRoutes
}
