// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package models

// Injectors from user.wire.go:

func InitializeNewUserProvider() *User {
	user := NewUserProvider()
	return user
}
