// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package login

// Injectors from account.wire.go:

func InitializeNewAccountProvider() *Account {
	account := NewAccountProvider()
	return account
}
